### ISSUE TITLE
Add gender support to SortingHat

### ISSUE THREAD

**Issue by dicortazar** [chaoss/grimoirelab-sortinghat#128]
According to https://github.com/chaoss/grimoirelab/issues/69, there is a need to support gender in the GrimoireLab toolchain. And SortinHat is one of the pieces of this toolchain.

With this respect, this task expects as outcome to have a new entry in the profile of the community member that could be accessible by the CLI o the API.

This is just an initial requirements, so further discussion could be part of this ticket.

**Comment by sduenas** [comment]
As gender is a "hot topic" where everyone can have strong opinions regarding what is gender and what is not, I think `sortinghat` should be as flexible as possible. I suggest to add a free text field on `profiles` table, where the user can write whatever she wants.

For `autogender` command, we can fill the profile using `male` or `female` terms. The assignation wll be based on guessing whether the name of an unique identity is usually used either in men or women. The command can use a third-party service or a dataset like the ones described in this link: https://stackoverflow.com/questions/1803628/raw-list-of-person-names

@dicortazar thoughts?

**Comment by dicortazar** [comment]
As suggested by @sduenas I'd go for a free text field and this would contain basically information coming from potentially any place. It's true that we need some common way of naming the gender, but this mainly depends on the project and the people in that project.

So far what we're using is genderize.io, although there are specific libraries for instance in Python that we can use for this. That 'autogender' command may fill three options: male, female, unknown.
