### ISSUE TITLE
Unclear message when initializing a database

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-sortinghat#129]
When successfully initializing a SortingHat database, a log error is shown to the user. 
Should this information be reported in a different way?

https://github.com/chaoss/grimoirelab-sortinghat/blob/b6f8031174e8e82b7141ea9cfcddc75af9d91d04/sortinghat/cmd/init.py#L100

**Comment by jgbarah** [comment]
See #126 where I propose a fix for this (just removing the message, which I also find annoying).
