### ISSUE TITLE
Organizations of projects 

### ISSUE THREAD

**Issue by Avfdo1994** [chaoss/grimoirelab-sortinghat#139]
Sortinghat is not able to identify the organizations of projects. Is it possible to add the organizations of projects in the projects.json file or is there another way?

**Comment by jgbarah** [comment]
Could you please clarify to which "organizations of projects" do you refer, maybe with an example?

**Comment by sduenas** [comment]
I think this is a question for grimoirelab global repository. The way to add organizations to SortingHat is either running `sortinghat orgs --add <org>` or loading them from a SortingHat file with `sortinghat load <file>`. (see https://github.com/chaoss/grimoirelab-sortinghat#import--export)

With `mordred` you can load this file as well.

**Comment by Avfdo1994** [comment]
When I tried using Sorting Hat it wasn't able to identify and merge when an author has multiple identities

**Comment by jgbarah** [comment]
I'm not completely sure if you're asking about this, but just in case. Identifying organizations depend on the data sources you have. For git repositories, usually you have email addresses, which in certain cases can be mapped to organizations. For that, you can use a `orgs.json` file, such as [the one we use for the grimoirelab/* containers](https://github.com/chaoss/grimoirelab/blob/master/docker/orgs.json).

But this will not resolve addresses such as `xxx@gmail.com`, and will be of little help in identifying people with the same identity. For that, you can use a `identities.yaml` file. Again, you can use as a template [the one we use for the grimoirelab/* containers](https://github.com/chaoss/grimoirelab/blob/master/docker/identities.yaml).

Was this what you were asking for?

**Comment by Avfdo1994** [comment]
Is it possible to assign the organization of a repository using SortingHat?

**Comment by sanacl** [comment]
Hi @Avfdo1994, 
I think we could be talking about different topics.

In case you are asking about the organizations/groups/companies assigned to any contributor, the way the tool assign organizations is:
- based on the domain. E.g. the email luis@bitergia.com when Bitergia organization is created with the domain bitergia.com will be enrolled to Bitergia after executing sortinghat affiliate. If you are using it with Mordred it will do it automatically if the proper options are included.
or 
- specified using the YAML input Jesus mentioned above. E.g. you can say that the contributor John with email j.smith@gmail.com works for OpenBlahBlah
- specified using the sortinghat command 'enroll' so you can enroll any contributor available in the database to the desired company

.. if you are asking about creating a group of repos (similar to github organizations) you'll need to add them in the projects.json. Example: https://gitlab.com/Bitergia/c/CHAOSS/sources/blob/master/projects.json

I hope it sheds some light :)

**Comment by Avfdo1994** [comment]
Thanks for the help guys! :)
