### ISSUE TITLE
Adding Countries to sortinghat database

### ISSUE THREAD

**Issue by olblak** [chaoss/grimoirelab-sortinghat#140]
Hi,
Is there any other way than sql queries to add country code to a sortinghat db?

**Comment by sduenas** [comment]
So far countries are added using the contents of [sortinghat/data/countries.csv](https://github.com/chaoss/grimoirelab-sortinghat/blob/master/sortinghat/data/countries.csv). This file is read when a new database is created with the command `init`. You can add anything you want to this file.

This file contains the ISO 3166 countries list. Not sure whether it's outdated or not but my guess is it shouldn't be needed to add more countries.

What are you trying to do?

**Comment by olblak** [comment]
Just add countries, because mordred automactically create tables/columns in sortinghat, I never tried to use ```sortinghat init```

**Comment by sduenas** [comment]
I thought `mordred` created sortinghat database calling to `init` command but maybe I'm wrong.

@acs am I right?

**Comment by acs** [comment]
> I thought mordred created sortinghat database calling to init command but maybe I'm wrong.
> 
> @acs am I right?

You are right. https://github.com/chaoss/grimoirelab-mordred/blob/master/mordred/task_identities.py#L68
