### ISSUE TITLE
grimoirelab2sh produces an invalid json file: Attribute gender_acc not found

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sortinghat#143]
Latest changes have broken the tool `grimoirelab2sh` due to changes in the JSON format. Those changes seem to be related to the gender information

```
# sortinghat ... load --identities /tmp/ossn.json -m github
Error: invalid json format. Attribute gender_acc not found
```

**Comment by acs** [comment]
Already fixed with:

https://github.com/chaoss/grimoirelab-sortinghat/pull/142

Could you confirm it?

Closing the ticket. Reopen it if you have issues related to this PR.
