### ISSUE TITLE
GitHub releases out of date

### ISSUE THREAD

**Issue by jayvdb** [chaoss/grimoirelab-sortinghat#207]
https://github.com/chaoss/grimoirelab-sortinghat/releases has 0.7.0

https://pypi.org/project/sortinghat/ has 0.7.6

Also it would be great if tests could be added to the sdist uploaded to PyPI so they can be used for testing by distros.

At the moment there is no way to get a 0.7.6 tarball with the tests, so I can only package 0.7.0, which is a bit old.

**Comment by jayvdb** [comment]
Also 0.6.9 `setup.py` uses `super().initialize_options()` which is Python 3 only syntax.  The wheel might have been able to run on Python 2, but it isnt installable from source on Python 2.

**Comment by sduenas** [comment]
Hi, thanks for your comment. I'll check that.

By the way, I don't really understand why you need a release in GitHub as a tarball if you are already using packages in pypi. Can you give me more context so I can understand your use case?

**Comment by jayvdb** [comment]
When building a package for a distro (i.e. a deb or an rpm), we need sdists with tests to verify it is working correctly.

Specifically I want to upgrade this package
https://build.opensuse.org/package/show/devel:languages:python/python-sortinghat
But I dont submit upgrades that dont have tests, as I dont want to break other dependencies.

Also I really want an sdist of 0.6.9 because that is the last release to support Python 2, and openSUSE automatically builds two rpms, one for py2 and one for py3, so the build will fail for 0.7.0+ .  My fork is at
https://build.opensuse.org/package/show/home:jayvdb:grimoirelab/python-sortinghat

**Comment by jayvdb** [comment]
https://github.com/chaoss/grimoirelab-sortinghat/tree/8dfd61d10d78f27e191f8c805cf73e8980471478 has the same source in /sortinghat as the PyPI 0.6.9 sdist.

**Comment by jayvdb** [comment]
I am quite confident that the tests didnt pass on 0.6.9 for Python 2.7 .
```
sortinghat/utils.py", line 115, in to_unicode
    cs = [c for c in unicodedata.normalize('NFD', s)
TypeError: normalize() argument 2 must be unicode, not str
```

I'll need to dig a little deeper, and maybe try a few other earlier releases, to see if I can find which is the version to pass the tests on Python 2.7.  Or maybe the Travis CI build list can give a clue.

**Comment by sduenas** [comment]
The last release that worked with Python 2.7 was 0.6.4. See it on Travis: https://travis-ci.org/chaoss/grimoirelab-sortinghat/builds/389337900

This is the Travis build where we removed Python 2.7: https://travis-ci.org/chaoss/grimoirelab-sortinghat/builds/394476898

Sorry but we don't produce yet releases in GitHub for this minor versions. I don't have any problem to include the tests within the tarballs while they weren't included inside the eggs or wheel packages.
@jgbarah do you know if there's a way to do this?

In any case, is it so important to have packages for 2.7? 2.7 support finishes in less than 6 months.

**Comment by jayvdb** [comment]
Python 2 is supported until the EOL, so distros usually keep using versions that are supported by Python 2 until then, otherwise they need to support two different versions of the same package.  Exceptions are being made to that rule, but only in exceptional cases such as `pytest` which has switched to Python 3 only.

Thanks, I'll try v0.6.4, which is enough for my needs hopefully as grimoire-elk says it needs >= 0.6.2

**Comment by jgbarah** [comment]
> @jgbarah do you know if there's a way to do this?

Do you mean having the tests in the tarballs, but not in the pip packages? Something else?

**Comment by jayvdb** [comment]
`MANIFEST.in` controls the sdist.  `check-manifest` is a good tool to ensure the manifest is complete.   The wheel will not include the tests- it ignores the `MANIFEST.in`

**Comment by jgbarah** [comment]
Thanks for the clarification, @jayvdb. OK, now I see that you are referring to the sdist package.

I'm not in favor of including tests in sdist, since that means ovebloating it a bit. However, if this is a requirement for distros, I think we could do it... But would it be useful for you if we include tests in the sdist for the next minor release?

**Comment by jgbarah** [comment]
> Python 2 is supported until the EOL, so distros usually keep using versions that are supported by Python 2 until then, otherwise they need to support two different versions of the same package. Exceptions are being made to that rule, but only in exceptional cases such as `pytest` which has switched to Python 3 only.

Some time ago we decided that GrimoireLab was to support only Python3, and at some time, since SortingHat has a use mainly in its context, and is a part of GrimoireLab now, we decided to do the same for it. I'm sorry if that breaks things. This transition to Python3 is being a bit of a problem :-(

**Comment by pgajdos** [comment]
Hi,
I have stumbled over this issue as well, could you please consider to look at it? I would like to either use correctly tagged release from github or (better) use pypi tarball which would contain tests.
Thanks for consideration!

**Comment by sduenas** [comment]
I fixed this some months ago in every component of GrimoireLab. The problem is we haven't generated new packages in a while.

@jgbarah would you mind to generate new packagest for pypi?

**Comment by jgbarah** [comment]
I'm having some trouble in generating packages for all of GrimoireLab, apparently due to problems with scipy as a dependency. I'm still digging at it, could be an issue with my specific setup, but it is taking too long to figure out. I'm trying to give this as much priority as possible.

**Comment by sduenas** [comment]
This was already fixed when we released the new version of sortinghat.
