### ISSUE TITLE
[Bug] Grimoire stack itesm 'sortinghat' and 'elk' incompatible

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-sortinghat#209]
This repo requires pandas 0.22.0 (via `==` operator): https://github.com/chaoss/grimoirelab-sortinghat/blob/master/setup.py#L111.
ELK requires pandas 0.18.1 (also via `==` operator): https://github.com/chaoss/grimoirelab-elk/blob/master/setup.py#L85.
It is impossible to install them both due to that.
Changing the requirement for EKK from ``==0.18.1` to `=>0.18.1` solves the issue.

**Comment by lukaszgryglicki** [comment]
Ping?

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki , I missed this bug today. I'll provide a fix in ELK

**Comment by lukaszgryglicki** [comment]
Thanks.

**Comment by lukaszgryglicki** [comment]
Maybe worth adding some test for the entire package?
Like build a docker image with all `chaoss` tools installed together and then just invoke every single one and see if it runs or stack dumps python error...

**Comment by valeriocos** [comment]
It sounds like a good idea (cc @sduenas @jgbarah)

**Comment by valeriocos** [comment]
Closing this issue, since the PR in ELK has been merged
