### ISSUE TITLE
Implement functions to add/remove domains in api.py

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#214]
As in `Organizations` (see #213), the API does not have methods to add or delete `Domain` objects on a higher level than the database API.

The objective of this task is to develop these functions like `add_identity` or `delete_identity`.

**Comment by mafesan** [comment]
I have submitted a PR which aims to solve this issue: https://github.com/chaoss/grimoirelab-sortinghat/pull/217.

**Comment by jsmanrique** [comment]
Once this is supported, wouldn't it be nice to have ASAP such feature supported by HatStall?

Related issue: https://github.com/chaoss/grimoirelab-hatstall/issues/68

**Comment by sduenas** [comment]
Fixed by #217
