### ISSUE TITLE
Export log with the operations

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#220]
After adding the history of changes (see #145) to Perceval, every operation performed by the system is logged. This history is really useful because allows to recreate the state of every identity or organization. But, to do it, we need to export data in a useful format that could have read and imported later by the system.

The goal of this task is to provide the necessary methods to export the history of changes, probably using GraphQL.

**Comment by mafesan** [comment]
I am testing a first approximation to solve this issue. The idea is to obtain the list of operations using a GraphQL query. The list is returned ordered by the `timestamp` field and returns all the fields from the `Operation` model, converting the `args` parameter (A serialized JSON object) into a string.

This is how the query would look like:

```
query{
  operations{
    ouid
    opType
    entityType
    target
    timestamp
    args
  }
}
```

It would return something like this:

```
{
  "data": {
    "operations": [
      {
        "ouid": "56aa0978661e44e2a523812df33841e3",
        "opType": "ADD",
        "entityType": "organization",
        "target": "Example",
        "timestamp": "2019-11-12T11:14:37.267654+00:00",
        "args": "{\"name\": \"Example\"}"
      },
      {
        "ouid": "7219bb17541a47b58c9651dc069653af",
        "opType": "ADD",
        "entityType": "unique_identity",
        "target": "6cb6b834379c0af7032e09105d19f91a0215372c",
        "timestamp": "2019-11-12T11:14:47.448120+00:00",
        "args": "{\"uuid\": \"6cb6b834379c0af7032e09105d19f91a0215372c\"}"
      },
      {
        "ouid": "ba6a6e19f6064841b89db8f07c48ce90",
        "opType": "DELETE",
        "entityType": "organization",
        "target": "Example",
        "timestamp": "2019-11-12T11:14:55.827110+00:00",
        "args": "{\"organization\": \"Example\"}"
      },
      {
        "ouid": "a1a9b3c161b24397b16218013f9fa4e5",
        "opType": "UPDATE",
        "entityType": "profile",
        "target": "6cb6b834379c0af7032e09105d19f91a0215372c",
        "timestamp": "2019-11-12T11:14:59.184597+00:00",
        "args": "{\"is_bot\": true, \"uidentity\": \"6cb6b834379c0af7032e09105d19f91a0215372c\"}"
      }
    ]
  }
}
```

---

Some extra considerations:
* If this is going to be an internal functionality, maybe it is not necessary to ask for all the fields from the `Operation` object.
* Another solution could be to return the list of **Transactions** so we can get the set of  **Operations** associated with each of them. I see this more useful just in the case this is information is going to be displayed to the user, as it might help to understand the context under a set of operations were performed (i.e., merge identities).

Please, let me know your opinion about this. Thanks in advance!

**Comment by sduenas** [comment]
Ok, so maybe we should consider to have both queries, one for **Transactions**, another one for **Operations**. That will be more flexible and we can decide later how to use them.

**Comment by mafesan** [comment]
Thank you @sduenas!

I have added a query for **Transactions** too. Here is how it looks like:
```
query {
    transactions{
      name
      createdAt
      tuid
    }
}
```

This query would return data in this format:

```
{
  "data": {
    "transactions": [
      {
        "name": "add_identity",
        "createdAt": "2019-11-13T13:00:36.632459+00:00",
        "tuid": "3c851855c6fe4e0eae78b44d9571c787"
      },
      {
        "name": "merge_identities",
        "createdAt": "2019-11-13T13:01:32.111867+00:00",
        "tuid": "d0c29bf7c48f45f59d603af9c0690af7"
      }
    ]
  }
}
```

Both queries can now be combined and they support filtering for most of their fields. These are the fields which can be used for filtering:

| Query | Fields  |
| ------ | ------ |
| `operations`   |  `ouid`, `opType`, `entityType`, `target`, `from_date` and `to_date` (`timestamp`)  |
| `transactions`   |  `tuid`, `name`, `isClosed`,  `from_date` and `to_date` (`createdAt`)  |

This would be an example of a query combining the two new queries including some filters for the main query:

```
query {
  operations(
    filters:{
      opType:"DELETE",
      entityType:"organizations",
      fromDate:"2019-11-13T13:01:32.152416+00:00"
    })
   {
    ouid
    opType
    entityType
    target
    timestamp
    args
    trx{
      name
      createdAt
      tuid
    }
  }
}
```

Now I'm working on the unit tests for these changes.

**Comment by mafesan** [comment]
@sduenas The PR for this feature is ready for review: https://github.com/chaoss/grimoirelab-sortinghat/pull/223. Thanks!
