### ISSUE TITLE
GraphQL pagination

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#222]
So far, we haven't included any method for paginating the results retrieved in a GraphQL query. Due to the size of the normal databases this is a basic feature needed to operate the service. We need to define a pagination method shared by all the possible queries:

Some info:
* https://graphql.org/learn/pagination/
* https://codeburst.io/graphql-pagination-by-example-part-1-15ec3313ae08
* https://codeburst.io/graphql-pagination-by-example-part-2-2803802ef23a
* https://spectrum.chat/graphql/general/pagination-best-practices~5bd5a4b1-de62-4a15-afb0-befac23db3f6
* https://medium.com/react-native-training/building-chatty-part-5-pagination-with-graphql-23a25fc9f0bf
* https://medium.com/@mattmazzola/graphql-pagination-implementation-8604f77fb254

**Comment by mafesan** [comment]
As a first approach, we have decided to implement pagination using offsets and limits.

The idea is to add the `offset` and `limit` parameters as filters for the queries that are already defined. Then, we will filter the search in Django to mimic the behavior of performing a query like `SELECT * FROM uidentities LIMIT 5 OFFSET 10`. This would be made by defining a new type (including the `offset` and the `limit` fields by default) which will serve as parent of the rest of filter types, then adding a method performing this filtering and calling inside each query resolver.

**Comment by mafesan** [comment]
I have submitted a draft PR with some of this changes, please check: https://github.com/chaoss/grimoirelab-sortinghat/pull/225.

**Comment by mafesan** [comment]
The PR https://github.com/chaoss/grimoirelab-sortinghat/pull/225 is now ready for review. Thanks!

**Comment by sduenas** [comment]
Fixed by #225.
