### ISSUE TITLE
port in test_connection_error() is hardcoded

### ISSUE THREAD

**Issue by pgajdos** [chaoss/grimoirelab-sortinghat#226]
Hi, in `test_cmd_init.py`, there is `3306` hardcoded on two places as a port and this fails the  `test_connection_error` if another port is chosen on mariadb side and in `tests/tests.conf`. I guess `self.kwargs['port']` was meant to be used (despite the test name).

**Comment by valeriocos** [comment]
thank you @pgajdos for reporting this issue!

**Comment by pgajdos** [comment]
Thanks @valeriocos for fixing it.

**Comment by valeriocos** [comment]
you're welcome @pgajdos !
