### ISSUE TITLE
Unify omits blacklist when using email algorithm with `--no-strict-matching`

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sortinghat#228]
Having a Sortinghat database with blacklisted strings (emails) and executing the unify method with the matching algorithm `email` and `--no-strict-matching` produces and unexpected result. The unified identities do not use the blacklist so the identities with those values are merged.

How to reproduce:
* having a SH database add some emails to the blacklist with identities that are not merged
* merge by email with `--no-strict-matching`
* the result will be unified identities even when the email is present in the blacklist

**Comment by sduenas** [comment]
The error is `email.py` does not check the blacklist when `--no-strict-matching` is active. This is the missing code, that is avaliable in `email_name.py`.

https://github.com/chaoss/grimoirelab-sortinghat/blob/master/sortinghat/matching/email_name.py#L142
https://github.com/chaoss/grimoirelab-sortinghat/blob/master/sortinghat/matching/email_name.py#L177
