### ISSUE TITLE
[muggle] Perform authenticated GraphQL queries in Graphene-Django

### ISSUE THREAD

**Issue by mafesan** [chaoss/grimoirelab-sortinghat#233]
The goal of this issue is to explore how to perform authenticated GraphQL queries in Graphene-Django, which are the different levels of permissions and how to apply them to a SortingHat database.

**Comment by mafesan** [comment]
I have submitted a PR adding support for performing authenticated queries which is now ready for review: https://github.com/chaoss/grimoirelab-sortinghat/pull/234. Thanks!

**Comment by sduenas** [comment]
Fixed in #234 .
