### ISSUE TITLE
[muggle] Add an atomic method to split identities

### ISSUE THREAD

**Issue by mafesan** [chaoss/grimoirelab-sortinghat#237]
Similar to the method for merging identities, this method should also accept a list of identities as input, so multiple identities can be splitted at once. This operation must be atomic, so we may need to check if this causes any consistency errors.

This issue is related to https://github.com/chaoss/grimoirelab-sortinghat/issues/236.

**Comment by mafesan** [comment]
I have submitted a PR for this feature, which is now ready for review: #250 . Thanks!

**Comment by sduenas** [comment]
Fixed in #250.
