### ISSUE TITLE
[muggle] Add lock feature for unique identities

### ISSUE THREAD

**Issue by mafesan** [chaoss/grimoirelab-sortinghat#238]
The idea is to have, per unique identity, a property called "locked" which can be set to `True` or `False`. 

If the unique identity is `locked`, it means it cannot be modified, i.e.: no other identities will be merged in it or removed from it, no enrollments can be added, removed or modified, and its profile cannot be modified either.

**Comment by mafesan** [comment]
I have submitted a draft PR with most of the changes for this feature, without including the unit-tests.

I have a question about the following case: When a given organization is removed, the corresponding enrollments are removed too (deleted on cascade). If a given unique identity which is locked contains an enrollment of the organization being removed, should this operation be allowed?

**Comment by sduenas** [comment]
Yes, it should be. Otherwise there will be an empty foreign key which in our model is an error.

**Comment by sduenas** [comment]
Fixed by #252
