### ISSUE TITLE
No requirements.txt specified.

### ISSUE THREAD

**Issue by snack0verflow** [chaoss/grimoirelab-sortinghat#246]
Is this by design? While running micro-mordred I had to install a bunch of python modules like sqlalchemy, jinja2 etc

**Comment by valeriocos** [comment]
Thanks @snack0verflow for the pointer! Sortinghat uses only the setup.py to install its dependencies (https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py/49684835). However, for consistency reasons with the other GrimoireLab repos, we could add the requirements.txt to sortinghat, WDYT @sduenas ?

**Comment by sduenas** [comment]
Yeah, you can add it. No problem.

**Comment by snack0verflow** [comment]
Should I raise a PR? Do I need to follow any format?

**Comment by valeriocos** [comment]
Yes, please submit a PR, thanks. There is no specific format.

**Comment by snack0verflow** [comment]
@valeriocos  Raised PR #247
