### ISSUE TITLE
Move should only work with unique identities that have 2 or more identities

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#265]
When `from_id` is the only identity of a unique identity, move operation should not work because a unique identity will be orphan. The operation should be `merge` instead. 

There's also another option which will consists on remove the unique identity and move only the identity.

**Comment by mafesan** [comment]
I have just submitted PR https://github.com/chaoss/grimoirelab-sortinghat/pull/267 fixing this issue.

**Comment by sduenas** [comment]
Fixed by #267.
