### ISSUE TITLE
[doc] Add examples to deal with the SortingHat API via Python

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-sortinghat#284]
The documentation at https://github.com/chaoss/grimoirelab-sortinghat#basic-commands could be complemented with equivalent examples using Python. These examples could go to another section called `Basic API calls`.

Examples of some calls are alredy in ELK: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/sortinghat_gelk.py

**Comment by valeriocos** [comment]
@animeshk08 if you want to explore Sortinghat, this could be a good first issue. Let me know if you are interested in it.

**Comment by animeshk08** [comment]
Sure. I will start working on this :)

**Comment by valeriocos** [comment]
Great, thanks @animeshk08 ! If you are interested in reading about sortinghat, feel free to have a look at: https://www.researchgate.net/publication/331088184_SortingHat_Wizardry_on_Software_Project_Members
