### ISSUE TITLE
[muggle] Define component to show individuals data

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#298]
This component must show the list of identities and organizations linked to an individual. Also, it should display other information such as the uuids and whether is a bot or not. To implement it, we should extend the `IndividualCard` component.

**Comment by sduenas** [comment]
This design might be useful to show the list of identities:

![imagen](https://user-images.githubusercontent.com/833352/83152340-fec95980-a0fd-11ea-85a9-cfceda4aca6a.png)

**Comment by jsmanrique** [comment]
LGTM.

I would suggest to fix the height of the component, and to add a vertical scroll bar if needed.

Could the list work like an accordion? I mean, it could appear as it is, and by clicking in the platform icon that section collapses to something like:
``
(icon) {Platform} (number of identities)
(icon) {Platform} (number of identities)
(icon) {Platform} (number of identities)
```

**Comment by sduenas** [comment]
> LGTM.
> 
> I would suggest to fix the height of the component, and to add a vertical scroll bar if needed.
> 
Yes, we should do that. In any case, take into account organizations will go after this so will probably need to add the vertical bar outside of both components. 

> Could the list work like an accordion? I mean, it could appear as it is, and by clicking in the platform icon that section collapses to something like:
> ``
> (icon) {Platform} (number of identities)
> (icon) {Platform} (number of identities)
> (icon) {Platform} (number of identities)

Yes, I was thinking exactly the same. I can create a version using subgroups of list like in [here](https://vuetifyjs.com/en/components/lists/#nested-lists).

**Comment by sduenas** [comment]
This image shows how organizations data might look like.

@jsmanrique, What do you think about it? Anything else we should add?

![imagen](https://user-images.githubusercontent.com/833352/84405337-483e9c00-ac08-11ea-9c25-43e22cf6b505.png)

**Comment by jsmanrique** [comment]
ILGTM. I am a bit lost about how this is gonna be used, so, what about creating some use stories and sketches in separate tickets to help in the implementation phase?

**Comment by sduenas** [comment]
Fixed by #313.
