### ISSUE TITLE
Error: 3822, "Duplicate check constraint name 'top_domain_check'."

### ISSUE THREAD

**Issue by Ozanaydinn** [chaoss/grimoirelab-sortinghat#309]
While trying to initialize a database using the command sortinghat init, I get this error: 

sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (3822, "Duplicate check constraint name 'top_domain_check'.")
[SQL: 
CREATE TABLE domains_organizations (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	domain VARCHAR(128) NOT NULL, 
	is_top_domain BOOL, 
	organization_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT _domain_unique UNIQUE (domain), 
	CONSTRAINT top_domain_check CHECK (is_top_domain IN (0, 1)), 
	CONSTRAINT top_domain_check CHECK (is_top_domain IN (0, 1)), 
	FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE CASCADE
)DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_520_ci

I am using MySQL version 8.0.20, and Python version 3.6.1, and just recently installed Sortinghat.

**Comment by sduenas** [comment]
I thought this was fixed in https://github.com/chaoss/grimoirelab-sortinghat/issues/121#issuecomment-576864327. I wonder if it's related with MySQL version.

**Comment by Ozanaydinn** [comment]
Do you have any version recommendations that I should try? If that will fix the problem I can change the version.

**Comment by sduenas** [comment]
I use MySQL 5.7 (5.7.29 in Ubuntu). That works fine for me.

**Comment by Ozanaydinn** [comment]
Downloading the MySQL 5.7 version solved the issue for me, was able to generate a database without problem.
