### ISSUE TITLE
[ui] Show profile information when clicking on an individual card

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#326]
The app should show the **profile** (`ProfileCard` component) of an **individual** when an individual card is clicked on the grid component.

**Comment by evamillan** [comment]
I've made a drawer that pops up from the right side of the window when you click a card, showing the selected profiles. This is a demo of the behaviour:

![sortinghat](https://user-images.githubusercontent.com/26812577/94258794-b5fba300-ff2d-11ea-8724-47c9a6e22190.gif)

What do you think about it @sduenas ?

**Comment by sduenas** [comment]
@evamillan I thinkg it might work but I have some thoughts that we can discuss. 

- What happens if you click on several cards and they don't vertically fit on the page? Does a scroll bar show?
- I think there should be some kind of visual separator between the grid and the cards that show up. It will be easier to understand that there are several regions on the page.

**Comment by evamillan** [comment]
Would something like this work to separate the regions?
![imagen](https://user-images.githubusercontent.com/26812577/94276447-8efe9a80-ff48-11ea-9f57-899548dc12f7.png)

If the cards don't fit, only the drawer scrolls:
![scroll](https://user-images.githubusercontent.com/26812577/94276847-121ff080-ff49-11ea-9fa9-f92dc75635cc.gif)

**Comment by sduenas** [comment]
@evamillan I think that works nice.

**Comment by sduenas** [comment]
Fixed by #329 .
