### ISSUE TITLE
[ui] Drag and drop does not work for locked individuals

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#351]
To drag and drop individuals from the table to the workspace is not allowed. Clicking on "Save in workspace" on the actions menu works, though.

![See this example](https://user-images.githubusercontent.com/833352/96227638-ae5f7500-0f94-11eb-83ab-f495ae11e6e7.gif)

**Comment by evamillan** [comment]
I think rather than allowing drag and drop for locked individuals, we should disable the "save to workspace" action for them. From what I understand, the only action they should be allowed should be to unlock them, isn't it?

**Comment by sduenas** [comment]
> I think rather than allowing drag and drop for locked individuals, we should disable the "save to workspace" action for them. 

I think we still don't know what the best behaviour will be. I suggest to keep this issue open as reminder that this problem exists. We can work on this later.

> From what I understand, the only action they should be allowed should be to unlock them, isn't it?

Exactly but we will probably need to find a way to show that, so the user can understand they can not do any other thing.

**Comment by evamillan** [comment]
I think this was fixed by #468.

**Comment by sduenas** [comment]
Thanks. It was. GitHub doesn't close automatically the issues when they are in another branch, so I forgot to do it.
