### ISSUE TITLE
Implement Individuals search by term on GraphQL API

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#355]
The API should allow to search Individuals by a term, as in the `master` branch. The term should be searched on the fields `name`, `email`, `username`.

See the examples on the source code: https://github.com/chaoss/grimoirelab-sortinghat/blob/master/tests/test_api.py#L2618

Related to #340

**Comment by mafesan** [comment]
@sduenas I submitted a PR which is now ready for review: https://github.com/chaoss/grimoirelab-sortinghat/pull/380.

I have a question here: for the moment, this term is searched among the fields `name`, `email` and `username` from all the identities. Should this term be searched among the `Profile` fields too? Thanks!

**Comment by sduenas** [comment]
@mafesan sure, I think that will be very useful.

**Comment by sduenas** [comment]
Closed by #380.
