### ISSUE TITLE
Complete profile name with username value when name is not given

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#390]
When a new Individual is created its profile is created at the same time. When the name value is not given, the `name` attribute on the profile will be empty. It would be better to fill it with the value of `username`, it this one is given.

**Comment by mafesan** [comment]
@sduenas I have submitted the PR adding these changes, please have a look: https://github.com/chaoss/grimoirelab-sortinghat/pull/396. Thanks!

**Comment by sduenas** [comment]
Fixed by #396.
