### ISSUE TITLE
Search by last modified date

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#394]
The goal of this task is to allow to search `Individuals` by the date when they were modified the last time. We can use something similar to what GitHub does with its [advanced search](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/understanding-the-search-syntax).

The filter should allow to search Individuals that were modified:

- [ ] on a given date
- [ ] before/on a date
- [ ] after/on a date
- [ ] between a range of dates

**Comment by mafesan** [comment]
Hi @sduenas , I have submitted a draft PR with the main changes. I'm still working on the unit tests.

You will see the accepted date format is ISO 8601. I have included date + time, as other fields we have using dates need that format too. For instance, when adding an enrollment, the dates need to be following this format (e.g. `2008-01-01T00:00:00`).

**Comment by mafesan** [comment]
PR https://github.com/chaoss/grimoirelab-sortinghat/pull/401 is now ready for review, thanks!
