### ISSUE TITLE
Add installation guide

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#460]
The new version of SortingHat (`muggle` branch) doesn't have any documentation about the installation process. We need some documentation so users can install it.

**Comment by vchrombie** [comment]
Hi @sduenas, do you think we can close this now?

The required documentation is added through the PRs https://github.com/chaoss/grimoirelab-sortinghat/pull/492 https://github.com/chaoss/grimoirelab-sortinghat/pull/495.

**Comment by sduenas** [comment]
Fixed.
