### ISSUE TITLE
Gender recommendations

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#471]
The new SortingHat service should provide recommendations about gender based on individuals name. This is something that is available in previous versions using `autogender` command and `genderize.io` service.

**Comment by rohanreddych** [comment]
Hello, I am new to this community. Can I work on this? and can we use this https://github.com/chaoss/grimoirelab-sortinghat/blob/master/sortinghat/cmd/autogender.py ?

**Comment by sduenas** [comment]
Hi @rohanreddych, yes you can but you should work on something similar to: https://github.com/chaoss/grimoirelab-sortinghat/tree/muggle/sortinghat/core/recommendations . This feature is for the `muggle` branch on this repository.

**Comment by rohanreddych** [comment]
@sduenas is the `core/` directory the new graphql based server

**Comment by sduenas** [comment]
Fixed by #556
