### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#475]
GrimoireLab started to use GitHub actions for testing. That's already available in the current `master` branch but not in `muggle`. The goal of this task is to configure the repository so tests for both the backend and fronted are run each time a new PR is created or the code is added to one of the branches.

**Comment by vchrombie** [comment]
I think this issue can be closed now. WDYT @sduenas?

**Comment by sduenas** [comment]
Yes. Let's close it.

Fixed by #481.
