### ISSUE TITLE
ModuleNotFoundError when trying to run django server

### ISSUE THREAD

**Issue by rohanreddych** [chaoss/grimoirelab-sortinghat#484]
When i'm trying to run `python manage.py runserver` it throws an error of the sort 
`ModuleNotFoundError module 'settings' not found`.

https://github.com/chaoss/grimoirelab-sortinghat/blob/08161d54c55e99b88ad40d4557070ae75eb0c312/manage.py#L6

I changed the above line from `settings` to `config.settings.devel` it fixed the above error.

**Comment by vchrombie** [comment]
Hi @rohanreddych, it is expected behavior.

You can give it as an argument too, instead of changing the source code.
```
$ python manage.py runserver --settings=config.settings.devel
```

**Comment by rohanreddych** [comment]
Ah! I think should also be added to the new documentation.
Closing the issue.
