### ISSUE TITLE
mysqlclient version in requirements.txt causes an error while trying to run the server

### ISSUE THREAD

**Issue by rohanreddych** [chaoss/grimoirelab-sortinghat#486]
https://github.com/chaoss/grimoirelab-sortinghat/blob/321fbe2d257f45ee37582532ec39e777755204f5/requirements.txt#L7

This throws the error 
```AttributeError: module 'MySQLdb.constants.FIELD_TYPE' has no attribute 'JSON' while migrating in Django``` 
when trying to run `python manage.py runserver`.

I followed [this](https://stackoverflow.com/questions/63525904/attributeerror-module-mysqldb-constants-field-type-has-no-attribute-json-wh) and did `pip install mysqlclient==2.0.1` it is working fine now.

**Comment by sduenas** [comment]
Good catch.

By the way, we're going to start to deprecate `requirements.txt` in favour of `poetry`. Yesterday we added support for it. You can check how to install everything on this file: https://github.com/chaoss/grimoirelab-sortinghat/blob/muggle/.github/workflows/ci.yml.

If you want to contribute creating a PR increasing the version of that library it would be great.

**Comment by vchrombie** [comment]
Hi @rohanreddych, I couldn't reproduce this error after upgrading the Django version to `2.2`.

Also, I was successfully able to install and run the project (without any errors) after updating some dependencies (mentioned in the PR https://github.com/chaoss/grimoirelab-sortinghat/pull/490).

You can check the installation steps here, https://github.com/vchrombie/grimoirelab-sortinghat/tree/documentation.

Are you interested to try it out?

**Comment by rohanreddych** [comment]
I think you are using poetry as pointed out by sduenas . I was doing pip install requirements.txt. will check out your solutions.
