### ISSUE TITLE
Order individuals by lastUpdated field

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#488]
The API and the UI should allow users to order individuals by their last modification date. This should be sort in ascendant and descendant orders.

**Comment by AllMight2099** [comment]
Hey there! Can I take this issue up if no one's working on it?

**Comment by sduenas** [comment]
@evamillan is currently working on this.

**Comment by AllMight2099** [comment]
Hey @evamillan! Are you still working on this or can I take it up?

**Comment by evamillan** [comment]
@AllMight2099 I'm working on it :)

**Comment by sduenas** [comment]
Fixed by #505 .
