### ISSUE TITLE
SortingHat UI doesn't prefill `country` 

### ISSUE THREAD

**Issue by SteveKola** [chaoss/grimoirelab-sortinghat#503]
While creating a new identity via the UI, I noticed that the country section in the form is not prefilled nor is it a selectbox even though there is a tiny dropdown on the space.
And also, filling in a country name manually simply saves the country value as null - I noticed when I queried the data with GraphQL.

Is it that it has not been implemented yet?

**cc:** @sduenas @vchrombie

**Comment by sduenas** [comment]
We missed to include this part in the README file. After applying the migrations we need to apply the fixtures that are in the `fixtures` directory.

@vchrombie do you mind to open a PR to fix it?

**Comment by vchrombie** [comment]
As @sduenas commented, I could fix the bug by applying fixtures after migrations.

```
(.venv) $ ./manage.py makemigrations --settings=config.settings.devel
(.venv) $ ./manage.py migrate --settings=config.settings.devel
(.venv) $ ./manage.py loaddata sortinghat/core/fixtures/countries.json --settings=config.settings.devel
(.venv) $ ./manage.py runserver --settings=config.settings.devel
```

**Comment by vchrombie** [comment]
@SteveKola, can you check if the issue is resolved?

**Comment by SteveKola** [comment]
It works fine now. Thank you.
