### ISSUE TITLE
Before Route Enter authentication on Login route 

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [chaoss/grimoirelab-sortinghat#532]
At present, as before any route enters we are first verifying our authentication and then we allow the user to enter that route after authentication. 
For the Login route, the user is allowed in both the situation:
       1) When User Wants to Login
       2) When the User is already Logged In and has an authentication token in the store.

So, I think for the second case when a user has a valid authentication token then he/she should be redirected to the dashboard rather than that of the login route and allow to visit the login route only when it log out first.

This issue can be easily solved by updating some logic before each route enters inside the `index.js` file in the router folder.

I know this is not such a big issue for the present version, but just for the improvement of our tool, we can do this.

If you find it useful then I can work on it.

**Comment by evamillan** [comment]
I don't think there would be many instances of users visiting the `/login` route when they are authenticated, but in case they do, it could be useful to redirect them to the dashboard.

**Comment by SourabhSaraswat-191939** [comment]
@evamillan, So should I work on this?

**Comment by evamillan** [comment]
@SourabhSaraswat-191939 Yes, you can open a PR that adds the redirection :)

**Comment by SourabhSaraswat-191939** [comment]
@evamillan, I solved this issue but I don't know that whether I should add changes in my previous PR (#524) which is still open as a PR related to UI  
Or 
I should create a new branch to create new PR.
Or
Is there any other better way?

Please guide me for this.

**Comment by vchrombie** [comment]
> @evamillan, I solved this issue but I don't know that whether I should add changes in my previous PR (#524) which is still open as a PR related to UI

As it is a different issue, I would suggest opening a new PR with a new branch.
Let us know if you need any help.

**Comment by sduenas** [comment]
Closed by #537
