### ISSUE TITLE
Credentials are not removed from Store while logout

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [chaoss/grimoirelab-sortinghat#536]
**Issue**
At present, our Vue.Js application works fine but there is a `security issue`.

The issue is that after login when we try to logout, a logout() function called and in that function users credentials are removed from cookies and users get redirected to login page, but credentials remains unchanged in store (`vuex`) because there is no instruction in code to update store(vuex state) data while logout. The credentials remains unchanged in store till we reload our page, so on reloading new values are assigned or we can say current cookies values are assigned which is null(undefined) as we logout, which removes previous credentials.

We know that store data (Vue state/Vuex data) can only be seen on development mode using developers tools, it cannot be seen on Production mood. But it can be used as mentioned below. 

So the false practice can be attempted if a person after logging out of valid user, any how change (push) his route to "/" without refreshing his/her page then that person can still access everything as because that person have credentials of lastly login user available in store.

**Solution**
To solve this we only have to update store variables, as like mentioned below:-

```
this.$store.state.token=undefined;
this.$store.state.user=undefined;
```

If you find it useful then I can create a PR on this.

**Comment by sduenas** [comment]
Closed by #538 .
