### ISSUE TITLE
Script to migrate data from version 0.7.x to new version

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#542]
Due to data model has changed from one version to another and SQLAlchemy is not used anymore, we need to create a script that allows to export data and import it in the new sortinghat.

We think the best solution is to create a fixture file. This file can be imported directly using django commands. This would be even faster than creating export/import methods or to call mutations directly.

**Comment by zhquan** [comment]
@sduenas where we should save this script?

**Comment by sduenas** [comment]
Good question. Maybe a top folder called `utils`.

**Comment by sduenas** [comment]
Fixed by #543.
