### ISSUE TITLE
Create a Groups model to handle organizational hierarchies

### ISSUE THREAD

**Issue by Rashmi-K-A** [chaoss/grimoirelab-sortinghat#548]
As discussed in #541, a new model called `Group` needs to be created to store subdivisions/departments/groups of an organization. 

- [x]  Create model `Group`
- [x]  Implement `add_group`, `find_group`, `delete_group` methods in `db.py`
- [x]  Implement `add_group`, `find_group`, `delete_group` methods in `api.py`

**Comment by sduenas** [comment]
Fixed by #552 .
