### ISSUE TITLE
Extend UI to handle organizational hierarchies

### ISSUE THREAD

**Issue by Rashmi-K-A** [chaoss/grimoirelab-sortinghat#567]
This issue is to decide on how to extend the existing UI to allow users to add teams, and add users to teams.

**Comment by Rashmi-K-A** [comment]
Adding a couple of wireframes below for allowing users to add to teams. I'll add a different comment for how we are viewing the list of teams as well.

I want to point out that we also have teams that arent affiliated to any organization. 

I thought of separating out the teams which don't belong to any org as separate entities called "Unaffiliated groups" would handle the situation as follows:

![Blank diagram (5)](https://user-images.githubusercontent.com/39820442/126128287-11992af7-562a-4017-bb97-e72109b411a7.png)

Teams that belong to organizations can be added from the organization affiliation row itself.
Teams that do not belong to any organization would be added under the unaffiliated groups category.

To add teams at the time of creation, it could look something as below
<img width="592" alt="Screenshot 2021-07-19 at 4 21 42 PM" src="https://user-images.githubusercontent.com/39820442/126149256-292f0753-c361-4c36-a1c8-9e095cf895fc.png">

**Comment by Rashmi-K-A** [comment]
For viewing/creating teams, we would have all the teams  belonging to an org under the org's expanded view. There would be a View all button (its missing from this image) and clicking on that would open up a modal that would list all the subteams. Since a modal is a separate view, we can fit as many teams as we want in there.  The teams that dont belong to an org would be under the organizations sector like follows:

<img width="968" alt="Screenshot 2021-07-19 at 1 55 41 PM" src="https://user-images.githubusercontent.com/39820442/126334662-8f626185-9701-4a23-bf5f-923beab1ae5b.png">

**Comment by Rashmi-K-A** [comment]
Creating/editing teams using the org edit button (similar to domains):

<img width="399" alt="Screenshot 2021-07-19 at 12 35 29 PM" src="https://user-images.githubusercontent.com/39820442/126338722-45c36270-f846-4b63-84a0-38beff4e4ade.png">

**Comment by Rashmi-K-A** [comment]
The expanded user profile
![Blank diagram - Page 1](https://user-images.githubusercontent.com/39820442/126993086-bd310969-6db2-4c32-b513-208bc6914fff.png)


On clicking the edit icon or add team/ add group button, ![Blank diagram - Page 4](https://user-images.githubusercontent.com/39820442/126993017-fdaa3317-76b2-4b71-9b34-b6c38e6aa033.png)
Note: the add groups modal woudl show the inputs called 'Group' and 'Team name' not 'parent team' and 'team name'.



At the user create time, 
![Blank diagram - Page 5](https://user-images.githubusercontent.com/39820442/126993524-33580822-9326-4bfb-8171-3eb5d083a14b.png)

**Comment by Rashmi-K-A** [comment]
The organizations table would remain the same. The only addition is a teams subsection for each organization that would have a view all button that opens a modal displaying all teams in that organization. We could optionally display just the top level teams on the expanded section as well.

<img width="879" alt="Screenshot 2021-07-26 at 6 59 11 PM" src="https://user-images.githubusercontent.com/39820442/126996836-1cf36884-5016-4e51-ba04-06f4e06fe89d.png">

This modal would be where users come in to add, edit and modify the teams in an organization. A modified version of this would be used for unaffiliated groups as well. The example uses the v-treeview component.
<img width="781" alt="Screenshot 2021-07-26 at 6 59 25 PM" src="https://user-images.githubusercontent.com/39820442/126996882-0c9d430b-b04e-4058-803c-c789494f3a4d.png">

**Comment by sduenas** [comment]
> The organizations table would remain the same. The only addition is a teams subsection for each organization that would have a view all button that opens a modal displaying all teams in that organization. We could optionally display just the top level teams on the expanded section as well.
> 
> <img alt="Screenshot 2021-07-26 at 6 59 25 PM" width="781" src="https://user-images.githubusercontent.com/39820442/126996882-0c9d430b-b04e-4058-803c-c789494f3a4d.png">
> 
> This modal would be where users come in to add, edit and modify the teams in an organization. A modified version of this would be used for unaffiliated groups as well. The example uses the v-treeview component.
> 
> <img alt="Screenshot 2021-07-26 at 6 59 11 PM" width="879" src="https://user-images.githubusercontent.com/39820442/126996836-1cf36884-5016-4e51-ba04-06f4e06fe89d.png">

This might work. Are you working in a story for this part?

I think we also can give different terms for teams and groups, although they are stored the same way.

For example, groups can be those teams that are not linked to an organization. Teams are those that are linked to an organization.

**Comment by Rashmi-K-A** [comment]
@sduenas  I had started working on the user view of adding teams (the modal and the changes in the expanded user view) but I ll switch over to this if you are ok with it because ideally this should be done first. Eva suggested using a. different component for displaying hierarchies but I havent looked into it yet.

I agree about the names - I am calling them as you mentioned above. Am going to close this ticket and create two new ones - One for UI view for adding/editing/deleting teams&groups. Another for UI view for allowing users to add team info to individuals. is that ok?

**Comment by sduenas** [comment]
> @sduenas I had started working on the user view of adding teams (the modal and the changes in the expanded user view) because that view was pretty much confirmed but I ll switch over to this if you are ok with it because ideally this should be done first. Eva suggested using a. different component for displaying hierarchies but I havent looked into it yet.
> 
> I agree about the names - I am calling them as you mentioned above. Am going to close this ticket and create two new ones - One for UI view for adding/editing/deleting teams&groups. Another for UI view for allowing users to add team info to individuals. is that ok?

Yeah, please, keep working on what you were doing! Keep this one opened and open new specific ones.
