### ISSUE TITLE
Hide implementation details in teams model

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#569]
Some implementation details about how relationships between teams are stored in the database are exposed using the GraphQL API. End users don't need this information so it shouldn't be available.

For instance, fields such as `path` should't be accesible with the following query:

```
query teams {
  teams {
    entities {
      name
      path
    }
  }
}

{
  "data": {
    "teams": {
      "entities": [
        {
          "name": "test",
          "path": "0001"
        },
        {
          "name": "test2",
          "path": "0002"
        }
      ]
    }
  }
}
```

We need to determine which fields should be available and which not and block their access.

**Comment by evamillan** [comment]
Those fields are already excluded from the [Team type](https://github.com/chaoss/grimoirelab-sortinghat/blob/91fe8f6d9bd458b61d13354f3a0657974cea21ea/sortinghat/core/schema.py#L209).
