### ISSUE TITLE
Merge organizations

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#571]
Sometimes an organization takes over or absorbs other organizations. Sometimes the organization is the same but there was a mistake assigning the names. For these reasons, it would be nice to have the option to merge organizations. That means individuals enrolled in one organization will be automatically enrolled to the new one after the merge.

**Comment by xiao623** [comment]
Is there a plan to implement this feature? I had got the same probleams.

> Sometimes an organization takes over or absorbs other organizations.

Example: The OpenJS Foundation is an organization that was founded in 2019 from a merger of JS Foundation and Node.js Foundation

**Comment by sduenas** [comment]
We'll implement this for the new version of sortinghat.

**Comment by sduenas** [comment]
We're going to finally work on this feature.
