### ISSUE TITLE
[Database] The efficiency is low when calling method `search_unique_identities`

### ISSUE THREAD

**Issue by xiao623** [chaoss/grimoirelab-sortinghat#594]
https://github.com/chaoss/grimoirelab-sortinghat/blob/6ab43545fe7a646500b66e0b17f297a51228c9da/sortinghat/api.py#L855-L857

https://github.com/chaoss/grimoirelab-sortinghat/blob/6ab43545fe7a646500b66e0b17f297a51228c9da/sortinghat/api.py#L862-L866

As we can see, we use `join` and `like` to query an unique identity. If the number of unique identities are bigger, for example 10+K, it would take a long time (maybe 10+s) to get the result.

Are there any good ways to improve the performance? For example, using the graph database maybe helpful.

**Comment by sduenas** [comment]
Hi @xiao623 thanks for your comments. Currently we're working on a new version of this tool that uses django as an ORM. You can find it on `muggle` branch of this repository. Maybe you can check that code and comment any performance issue we might have.

**Comment by xiao623** [comment]
@sduenas 
OK. I will try the branch version. 
I hadn't read the code of the branch.
Do i need to change anything of my database? Or I just need to uninstall the `master` version and then change to use the new API? It is better that there are no change in my application.

**Comment by sduenas** [comment]
You have all the details here: https://github.com/chaoss/grimoirelab-sortinghat/tree/muggle#compatibility-between-versions

Take into account this version doesn't work with the other parts of the GrimoireLab platform yet. So I recommend you to follow the readme and probably use this new version inside a virtual environment if you want to give it a try.
