### ISSUE TITLE
Wrong label "Delete the selected items" when deleting from the list of individuals

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#632]
By clicking on the `Delete` button on the individuals list, the label should say `Delete the selected individuals?` instead of `Delete the selected items`.

![imagen](https://user-images.githubusercontent.com/833352/182832871-f9d8cb8b-75b0-48cb-aa1d-251b7eeed85b.png)

**Comment by evamillan** [comment]
Fixed by #644.
