### ISSUE TITLE
Visual cue to separate the expanded information on the individuals entry

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#636]
Right now, the horizontal line that separates on individual from its expanded view (identities and organizations) is barely visible.
It should be clear for the user where both sections start.

![imagen](https://user-images.githubusercontent.com/833352/182807218-2729e481-dece-487a-8130-d455936316e6.png)

Also, the expanded view should have a different color when the entry is selected.

**Comment by evamillan** [comment]
Fixed by #650.
