### ISSUE TITLE
Organization choices in the forms to assign organizations

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#639]
The forms to assign organizations to individuals should show show the list of organizations available. Due to the possible choices can be a very long list, these ones should be shown only when the user has introduced a minimum number of characters (e.g. 3 or 4 characters).

![imagen](https://user-images.githubusercontent.com/833352/182815299-3f1db83c-fa44-4a03-a4de-6fe6b853d794.png)

![imagen](https://user-images.githubusercontent.com/833352/182815361-570897fe-3829-4d89-a828-99718693e743.png)

**Comment by evamillan** [comment]
Fixed by #646.
