### ISSUE TITLE
get_unique_id() in sortinghat.api

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-sortinghat#71]
I guess we would need get_unique_id() in sortinghat.api. Its functionality would be, given an identity. return the corresponding uuid. This would be similar to the uuid returned by sortinghat.api.add_identity().

The rationale is as follows. One possible use of the api is to call add_identity whenever a new identity is found. If the identity is new to Sorting Hat, the new uuid will be returned, and the data source can be annotated with it. But if for some reason the identity is already known to Sorting Hat,  AlreadyExistsError will be raised, and i find no way of knowing about the uuid for that identity in the API.

The code would be straightforward, something similar to the first part of add_identity(), which checks whether there is a uuid already associated to the identity to insert.

**Comment by b-thebest** [comment]
Is this completed ?

**Comment by sduenas** [comment]
The current API methods return the UUID of the individual when an error is found. So this is not needed anymore.
