### ISSUE TITLE
Feature request: integrate github-readme-stats

### ISSUE THREAD

**Issue by Pablohn26** [chaoss/grimoirelab-sortinghat#730]
There is a pretty popular project named [github-readme-stats](https://github.com/anuraghazra/github-readme-stats)

I think would be interesting to integrate it on sortinghat when there is a GitHub identity to get something like the following: 

![image](https://user-images.githubusercontent.com/1228418/214851854-cbfea7e1-9eba-4fee-86be-d4bd68b2f17c.png)

Another option (instead of the image above) would be to add a button that opens a pop-up that shows the stats when the user wants to:

![image](https://user-images.githubusercontent.com/1228418/214856309-c961256a-9f4f-4d0a-a1d9-fc000fbd895f.png)

The URL to show the stats of the example is: 
> https://github-readme-stats.vercel.app/api?username=anuraghazra

**Comment by Pablohn26** [comment]
If we want to get the data querying directly to GitHub, rather that use the project, [here are the queries](https://github.com/anuraghazra/github-readme-stats/blob/60fae292a349cd3d92942dc56bf67778c213cb0d/src/fetchers/stats-fetcher.js#L42).

**Comment by sduenas** [comment]
SortingHat is not designed for that.
