### ISSUE TITLE
Feature request: Follow international standar ISO IEC_5218 for gender

### ISSUE THREAD

**Issue by Pablohn26** [chaoss/grimoirelab-sortinghat#734]
For gender storage, could we use current `Codes for the representation of human sexes` using the [ISO IEC_5218](https://en.wikipedia.org/wiki/ISO/IEC_5218) ? 

From [here](https://cdn.standards.iteh.ai/samples/81682/bc904312b1de4a0da93580c92e5d98fd/ISO-IEC-5218-2022.pdf):
![image](https://user-images.githubusercontent.com/1228418/217341541-a6a6b4d9-3967-44ca-8712-fbce2271ce07.png)

**Comment by evamillan** [comment]
@Pablohn26 That's a standard for sex, not gender.

**Comment by sduenas** [comment]
Yes, that's for sex and not gender. The gender field on SortingHat is a free-text field so everyone that uses it can set whatever they think they are.
Closing this issue.
