### ISSUE TITLE
Feature Request: Link from SortingHat to contributor's social profiles

### ISSUE THREAD

**Issue by Ruth-ikegah** [chaoss/grimoirelab-sortinghat#817]
A feature request to have a link to view contributors' social profiles in SortingHat. 

Use case: Users can quickly look at a contributor profile to get more information, for example GitHub profile

**Comment by GeorgLink** [comment]
To clarify, the goal is NOT to pull in social profiles into SortingHat, but to have a link or button to quickly go to the social profiles like GitHub profile.

**Comment by Ruth-ikegah** [comment]
> To clarify, the goal is NOT to pull in social profiles into SortingHat, but to have a link or button to quickly go to the social profiles like GitHub profile.

Thank you @GeorgLink! I have edited the issue, I will be adding an image soon

**Comment by dicortazar** [comment]
+1, I'm feeling the pain.

**Comment by sduenas** [comment]
We can close this ticket. We already have linkedin and github profiles. If we need more, we can open  tickets to include other profiles.
