### ISSUE TITLE
Forking and Cloning Issue 

### ISSUE THREAD

**Issue by Anmollenka** [chaoss/grimoirelab-sortinghat#832]
I am trying to setup developer installation steps for grimoire lab following https://chaoss.github.io/grimoirelab-tutorial/docs/getting-started/dev-setup/ setps.
After forking sorting hat repository,I am unable to clone it.
Facing the below issue
![image](https://github.com/chaoss/grimoirelab-sortinghat/assets/48198809/c924f41e-6647-435b-a2ba-941243831028)
Can someone help me with this

**Comment by sduenas** [comment]
I cloned your repository and I didn't find any problem. Try to do it again in another directory and see what happens. Also, you are using Windows. GrimoireLab is not going to work there. You should switch to Linux or Mac.

**Comment by Anmollenka** [comment]
Thanks @sduenas for your reply.It's working fine now
