### ISSUE TITLE
github2 is github. Display.

### ISSUE THREAD

**Issue by fioddor** [chaoss/grimoirelab-sortinghat#869]
SortingHat groups `github2` data source as _Other data sources_.

Being so prominent, users would expect to find `github2` in the GitHub block:

![imagen](https://github.com/chaoss/grimoirelab-sortinghat/assets/36269471/2e563b13-3cb8-41b4-b9a0-17dde9ee96bd)

**Comment by sduenas** [comment]
Starting from [GrimoireLab 0.15](https://github.com/chaoss/grimoirelab/releases/tag/0.15.0), the tag `github2` is no longer assigned to identities. 

To avoid these problems, I suggest to remove all these entries from the database and re-enrich the indices again.
