### ISSUE TITLE
Documentation: -d name not used with sortinghat init

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-sortinghat#87]
When running sortinghat with the `init` option and the `-d name` parameter, I get:

```bash
$ sortinghat -u jgb -p XXX -d sortinghatdb init
usage: sortinghat init <name>
sortinghat: error: the following arguments are required: name
```

But the `--help` option says:

```bash
$ sortinghat --help
usage: sortinghat [--help] [-c <file>] [-u <user>] [-p <password>]
                  [--host <host>] [--port <port>] [-d <name>]
                  command [<cmd_args>]
...
  -d DATABASE, --database DATABASE
                        name of the database where the registry will be stored
...
```

Therefore, it seems to imply that with `-d` you specify the database for sortinghat.

When running the help for the init option, I find how to do it:

```bash
$ sortinghat init --help
usage: sortinghat init <name>

Create an empty Sorting Hat registry.

positional arguments:
  name        Name of the database to store the registry
```

So, when running

```
$ sortinghat -u jgb -p XXX init sortinghatdb
```

it works.

But I would expect, given the help banner above, that `-d sortinghatdb` would work as well.

I  suggest removing the `name` option for init, and letting the database be specified via `-d`, as with other options.

**Comment by sduenas** [comment]
Init is no longer available in the new version of SortingHat.
