### ISSUE TITLE
[FR] Button to remove all pending/unapplied match recommendations

### ISSUE THREAD

**Issue by fioddor** [chaoss/grimoirelab-sortinghat#883]
The match recommendations are currently shared by manual processing and _Unify_ jobs.

This makes it very risky if _Unify_ jobs are scheduled because manual processing must end before the next scheduled run.

We might get way too many recommendations to handle manually. In such cases, _Unify_ jobs have to be de-scheduled to prevent massive uncontrolled unifications that could cause snowballs.

And match recommendations can only be removed by accessing the database directly. There's no option in the WUI, nor in the API to do so.

The most basic solution would be a button in the interface next to the recommendations count (or at least an option in the API) that disables (removes) the unapplied recommendations.

**Comment by canasdiaz** [comment]
We need to clarify whether the unify process merges recommendations created by the "recommendations" feature with a more "relaxed" matching algorithm.

**Comment by sduenas** [comment]
For this feature we need two things:

-  an API mutation to remove the existing recommendations
- a button on the UI to remove this recommendations
