### ISSUE TITLE
README out of date?

### ISSUE THREAD

**Issue by mhauru** [chaoss/grimoirelab-sortinghat#886]
I'm new to GrimoireLab and trying to learn my way around the components. I spotted this in the README:
>**Warning**: This is the developing branch of the new version of Sorting Hat. We're moving Sorting Hat into a service.
The documentation below would be totally incorrect or inaccurate. 

Git blame tells me that the notice is 6 years old, and I suspect no longer relevant. Would be useful to have it cleared and, if necessary, any out of date parts of the README removed.

**Comment by jjmerchante** [comment]
Hi @mhauru,

I believe this is from an older version of SortingHat. The README is updated without that comment: https://github.com/chaoss/grimoirelab-sortinghat/blob/master/README.md.

Please feel free to reopen the issue if you found it elsewhere.

Thank you!
