### ISSUE TITLE
The job list is empty

### ISSUE THREAD

**Issue by zhquan** [chaoss/grimoirelab-sortinghat#902]
I configured the automatic jobs (`affiliate` and `unify`) and I executed some jobs manually but I cannot see any job in the list.

- Automatic jobs
![image](https://github.com/user-attachments/assets/35b8e454-32f0-4a89-a387-2e2a36cc55b5)

- Job list
![image](https://github.com/user-attachments/assets/e46e250d-3350-4816-a85a-32ebbcea9c5a)

**Comment by sduenas** [comment]
That's probably because they have finished. Finished jobs have a small life time in the queue. When they are completed they are moved to a different registry.
I think we should fix this problem, though.

**Comment by evamillan** [comment]
The query that retrieves the job list is returning this kind of error in some cases:
```
{
	"errors": [
		{
			"message": "7740de3c-08f9-4e8c-8842-bd61132dbc16 not found in the registry",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			],
			"path": [
				"jobs"
			],
			"extensions": {
				"code": 9
			}
		}
	]
}
```

**Comment by jjmerchante** [comment]
This issue was fixed by this PR: https://github.com/chaoss/grimoirelab-sortinghat/pull/908
