### ISSUE TITLE
Show in the companies table the ones with enrollments

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-sortinghat#940]
If we think of SortingHat as the UI to polish up a standalone data set, there are several ways to improve the table on the right with the list of organizations/companies. Right now, that table is not useful, as it always shows the same companies and in most cases with 0 enrollments. What would be interesting is to see the companies with enrollments.

![imagen](https://github.com/user-attachments/assets/103631d5-1d00-4ecc-bece-39837017fdda)

In a conversation with @evamillan, she had a simple idea that can make it useful. The idea is to sort the companies by the number of enrollments. I would do this by default.

**Comment by sduenas** [comment]
That makes sense. One thing I think we can do is to make the columns actionable, so you can sort by any of the fields. But yes, by default, it should be sorted by the number of enrollments.
