### ISSUE TITLE
Init when database already exists

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-sortinghat#97]
This kind of code can be used for creating (and initializing) a SortingHat database:

```python
code = Init(**self.sh_kwargs).run(self.db_sh)

if code != 0:
    logger.warning("Can not create the SortingHat database")
```

But if the database already exists, it prints in the standard error output:

```
Error: Can't create database 'XXX'; database exists (err: 1007)
```

That's because of this code in Init.initializa(), in cmd/init.py:

```python
try:
    Database.create(user, password, name, host, port)

    # Try to access and create schema
    db = Database(user, password, name, host, port)

    # Load countries list
    self.__load_countries(db)
except DatabaseError as e:
    self.error(str(e))
    return e.code
```

Database.create() fails, rising DatabaseError exception, because the database already exists. This triggers the error, which gets printed in stderr because of:

```python
def error(self, msg):
    s = "Error: %s\n" % msg
    s = self._encode(s)
    sys.stderr.write(s)
```

This is confusing when it is likely that the database is already created. For example, in mordred, you need to always start with this code, but only the first time a configuration file for a dashboard is run, the database is created. The rest of the runs show that disturbing message, which seems to imply something went bad.

To avoid this, I suggest one of the following:

* re-raising the exception in Init.initialize(). But this could cause problems in code that assumes the exception is not re-raised. Maybe a parameter in Init() could control the behavior

* having a parameter in  Init to don't raise the exception if it is true (something like "ignore_if_created". By default it would have the current behavior. This is the one I like the most, since does not have side effects for existing code, and reflects what is expected in this scenario.

* having a parameter in Init to don't show the message, or control the function used to print it. By default it could be the current behavior

I can submit a pr if you agree on any of these.

**Comment by sduenas** [comment]
Init is not longer available in the new version of SortingHat.
